name: ci

on:
  pull_request:

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build ./cmd/server

      - name: Run unit tests
        run: go test ./...

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: fs
          format: table
          exit-code: 1
